### ISSUE TITLE
Баги в each_line if_line.

### ISSUE THREAD

**Issue by melihovv** [melihovv/yate#1]
```
{{#if condition}}
text1
{{/if}}
text2

Produce (if condition is true):
text1text2

{{#if_line condition}}
text1
{{/if_line}}
text2

Produce (if condition is true):
text1
text2
```

```
var context = {
  people: [
    {name: 'Homer'},
    {name: 'Bart'}
  ]
};

{{#each people}}
{{+name}}
{{/each}}

Produce:
HomerBart

{{#each_line people}}
{{+name}}
{{/each_line}}

Produce:
Homer
Bart
```
Notice there is no new line after 'Bart'

**Comment by melihovv** [comment]
Хах, а вебшторм тут без меня оказывается закрыл этот ишью давным давно)))
Ну, теперь он действительно закрыт.
Что изменилось, не считая рефакторинг, построение ast и его обход :
- теперь объявления переменных имеют блочную область видимости (а в javascript нет :))
- обращение к свойству объекта теперь такое `{{property}}`, а было `{{+property}}`.

**Comment by ahiddenseeker** [comment]
Переделал один файл на each_line, почему-то нарушается ваша спека, появляются лишние отступы внизу. Посмотрите, в чем может быть проблема.

**Comment by ahiddenseeker** [comment]
А нет, понял. Спека в первом комментарии просто сама содержит ошибку. Вспомнил, что оригинально давал, все верно. Хорошо, будем считать все проблемы закрытыми пока - реализованным шаблонизатором доволен.
