### ISSUE TITLE
Рефакторинг парсинга, вынесение основных функций за пределы его определения

### ISSUE THREAD

**Issue by ahiddenseeker** [melihovv/yate#2]
Необходимо отделить действия по генерации текста по шаблону от самого парсера, в идеале, построив AST.

**Comment by ahiddenseeker** [comment]
Добавьте документацию к внутренним функциям в compile, а то там довольно мало сейчас описания того, что происходит внутри (а точнее оно вообще отсутствует). Это поможет будущим поколениям разобраться в вашем коде.

**Comment by melihovv** [comment]
Хорошо, добавлю.
Я уже писал сюда, что изменилось, кроме заявленного, но оно каким-то образом удалилось. Напишу еще раз.

- объявление переменной теперь имеет блочную область видимости
- обращение к свойству объекта теперь такое `{{property}}`, а было такое `{{+property}}`

**Comment by ahiddenseeker** [comment]
Я понял, спасибо. Но issue стоит закрыть после внесения этого исправления.

**Comment by melihovv** [comment]
Я внес. Смотрите https://github.com/melihovv/yate/commit/448a4fa45884041eab374738562a3b8c8af4c393

**Comment by ahiddenseeker** [comment]
К сожалению, пока эта документация оставляет желать лучшего. Переоткрываю.
