### ISSUE TITLE
Пример из документации не работает при чистой установке

### ISSUE THREAD

**Issue by mamontov-cpp** [melihovv/yate#3]
Что делаю:
1. Создаю чистую папку
2. Делаю npm install melihovv/yate
3. В корне папки создал t.js с текстом из README
4. Запускаю node t.js . Выдает, что не может загрузить модуль.

**Comment by ahiddenseeker** [comment]
Судя по всему, ошибка в package.json, если в нем значение по ключу main заменить на lib/yate.js - ошибка меняется.

**Comment by ahiddenseeker** [comment]
Судя по-всему, ошибка в оформлении модуля, посмотрите, что здесь рекомендуют: http://darrenderidder.github.io/talks/ModulePatterns/ .

**Comment by ahiddenseeker** [comment]
Удалось уронить парсер, с довольно странной ошибкой, можете посмотреть в чем дело?

Сама ошибка: http://pastebin.ru/92bVxaHg

Тестовый скрипт и входные данные можно взять отсюда: https://github.com/ahiddenseeker/saddy-yate

**Comment by melihovv** [comment]
Поправил, теперь запускается.
В начале я когда README.md писал, думал, что буду объект экспортировать, а потом передумал и стал экспортировать функцию. Ну и в readme, конечно, забыл поправить. Извините)

**Comment by melihovv** [comment]
Насчет ошибки:
1. Вы когда с помощью fs читаете файл, он возращает буфер, а не строку. А при console.log() буфер приводится к строке неявно. Поэтому нужно сделать так:
`var template = fs.readFileSync("./duktapemethod.h.t").toString();`.
2. наверное, при формировании `variants` допущена ошибка, потому что `argscount` undefined, а `argscountp1` становится NaN поэтому.
![image](https://cloud.githubusercontent.com/assets/8608721/8811633/d8524a42-2fff-11e5-928b-9e7f21c65c4c.png)
3. синтаксис шаблона, насколько я понимаю, не верен. потому что вы используете, например, такую нотацию на 15 строке `{{#variants}}`. Как я понимаю, вы хотите пройтись по этому массиву. Тогда нужно писать вот так:
```javascript
{{#each variants}}
{{has_args}}
{{/each}}
```

**Comment by ahiddenseeker** [comment]
Ок, спасибо, что посмотрели. Вечером тогда сяду, отдельно поправлю. Приведу к вашему шаблону и проверю отдельно. 

Но проверки в 1 и 2 надо сделать - такую ошибку могу допустить не только я.

**Comment by ahiddenseeker** [comment]
Немножко обновил шаблон, не полностью.

>      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
>            ^
>SyntaxError: Expected assignment, condition, conditionLine, eachLoop, eachLoopLi
>ne, end of input, insertion or text but "{" found.

заверните исключение, сделайте, чтобы оно хотя бы показывало строку и символ, где ошибка. Непонятно где исправлять сходу.

**Comment by melihovv** [comment]
Сообщение об ошибке сделал, а проверки попозже сделаю.

**Comment by ahiddenseeker** [comment]
Сообщение об ошибке сейчас выглядит у меня так:

        throw Error('%d.%d: %s', e.line, e.column, e.message);
                                                    ^
Error: %d.%d: %s
    at Error (native)
    at compile (E:\Projects\yate-tests\node_modules\yate\lib\yate.js:20:53)
    at Object.<anonymous> (E:\Projects\yate-tests\t.js:30:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by ahiddenseeker** [comment]
Судя по всему, имелось ввиду вот это https://nodejs.org/api/util.html .

**Comment by ahiddenseeker** [comment]
Вытолкнул новую версию, завести пока не удалось. Я бы вообще убрал бы вызов compile и оставил бы только render - как раньше, сделав compile этапом внутри render.

**Comment by melihovv** [comment]
Ну, я сделал возврат функции render из функции compile, чтобы можно было один и тот же шаблон рендерить с разными контекстами. При этом не было необходимости строить заново ast. Так делает шаблонизатор handlebars.js, основанный на mustache. Ну если надо, могу вернуть, как было.

**Comment by ahiddenseeker** [comment]
Ок, тогда README поправьте - оно не соответствует тому, что вы описываете.

**Comment by melihovv** [comment]
А что именно там не соответствует? Вроде, все нормально.

**Comment by ahiddenseeker** [comment]
А, с моей стороны проблема. Ок, оставляем так.

**Comment by ahiddenseeker** [comment]
Вытолкнул новую версию, теперь почему-то в шаблоне не видно argscount, хотя он есть в объекте. Это я неправильно заполняю, или это баг?

**Comment by melihovv** [comment]
Он ошибку выдает или ничего не выводит вместо argscount?

**Comment by ahiddenseeker** [comment]
Он выдает ошибку, что его нет, хотя он есть.

**Comment by ahiddenseeker** [comment]
И заполнен числом. Скорее всего, что-то с типами, может быть это из-за того, что там число?

**Comment by melihovv** [comment]
Я склонировал ваш проект. Там у меня не было проблемы с argscount, но была с has_args. Если has_args оказывался false, то выдавалось, что has_args undefined. 
Эту проблему я починил, там просто была проверка неправильная. Проверялось содержимое переменной, а не определена ли она или нет.
В этом случае, наверное, когда argscount оказывался 0, то происходило то же самое.

**Comment by melihovv** [comment]
До конца ваш пример запустить не удалось.
У вас в args бывает либо not_last, либо last. А в шаблоне используются они оба. Ну а если переменная не определена в условии, бросается ошибка.
Это можно поправить конкретно для условия, если надо.

**Comment by ahiddenseeker** [comment]
Починил, но почему-то в цикле, когда number равен 0, вместо него подставляется undefined. Когда он ему не равен, то все ок. Можете посмотреть, в чем проблема? Вытолкнул новую версию.

**Comment by melihovv** [comment]
Да, я посмотрел.
Проблема оказалась в этом месте:
```javascript
getById: function (id) {
    return this.getFromSandBoxById(id) || context[id];
}
```
Тут когда из sandbox возращался ноль, смотрелось дальше в контексте. А там его нет.
Афигеть сколько багов уже нашлось. Я уже устал их исправлять.))

**Comment by ahiddenseeker** [comment]
С этим ок, сгенерировалось теперь верно, спасибо.
